site_name: 3D Particle Emitter Documentation
site_url: https://fancyducc.github.io/3D-Particle-System/

plugins:
  - search

theme:
  name: material
  favicon: images/Logo.png
  logo: images/Logo.png
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - toc.integrate
    - navigation.path
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  palette:
    # dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/lightbulb
        name: Toggle Light Mode

    # light
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Toggle Dark Mode

  font:
    code: Roboto Mono

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - codehilite:
      guess_lang: false
      default_lang: lua

extra_javascript:
  - javascripts/extra.js
extra_css:
  - css/custom.css

nav:
  - Home: getting-started.md
  - Installation: installation.md
  - Usage: usage.md
  - Properties:
      - Basic Properties: properties/basic-properties.md
      - Advanced Properties: properties/advanced-properties.md
      - Audio Properties: properties/audio.md
      - Light Properties: properties/light.md
      - Collision Properties: properties/collision.md
      - Trajectory Properties: properties/trajectory.md
      - Instability Properties: properties/instability.md
      - Function Properties: properties/event-functions.md
      - Debug Properties: properties/debug-properties.md
  - Prerequisites:
      - Part Cache: prerequisites/partcache.md
  - Free Templates: templatelist.md
  - Report an Issue: reportbugrequest.md
  - License: customprovisionlicense.md
